version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - s3://codepipeline-us-east-1-899556321063/hfpipeline/MyApp/spring-boot-aws-elasticbeanstalk.jar